**Lecture 7**

In [29]:
import numpy as np
my_list1 = [0,1,2,3,4,5]

In [10]:
my_array1 = np.array(my_list)

In [11]:
my_array1

array([0, 1, 2, 3, 4, 5])

In [12]:
my_list2 = [10,11,12,13,14,15]

In [13]:
my_list = [my_list1,my_list2]

In [14]:
my_array = np.array(my_list)

In [15]:
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [16]:
my_array.shape

(2, 6)

In [17]:
my_array.dtype

dtype('int64')

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((2,3)).dtype

dtype('float64')

In [22]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.empty((3,4))

array([[2.35541533e-312, 2.14321575e-312, 6.79038653e-313,
        1.29441743e-312],
       [9.33678148e-313, 2.12199579e-312, 2.56761491e-312,
        2.14321575e-312],
       [1.27319747e-312, 2.29175545e-312, 2.44029516e-312,
        6.79038654e-313]])

In [25]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [28]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

**Lecture 8**

In [31]:
5/2

2.5

In [33]:
arr = np.array([[1,2,3],[4,5,6]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [36]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
arr ** 3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [38]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

**Lecture 9**

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[2]

2

In [44]:
arr[2:8] = 9

In [45]:
arr

array([0, 1, 9, 9, 9, 9, 9, 9, 8, 9])

In [46]:
arr = np.arange(10)

In [47]:
arr1 = arr.copy()

In [52]:
arr_sp = arr[2:8]

In [49]:
arr_sp

array([2, 3, 4, 5, 6, 7])

In [50]:
arr_sp = 9

In [51]:
arr_sp

9

In [53]:
arr_sp

array([2, 3, 4, 5, 6, 7])

In [54]:
arr_sp[:] = 0

In [55]:
arr_sp

array([0, 0, 0, 0, 0, 0])

In [56]:
arr

array([0, 1, 0, 0, 0, 0, 0, 0, 8, 9])

In [57]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr_n = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))

In [61]:
arr_n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
arr_n[0][0]

1

In [64]:
arr_n[1]

array([5, 6, 7, 8])

In [70]:
arr_n[:2,[1,3]]

array([[2, 4],
       [6, 8]])

In [73]:
arr_2d = np.zeros((10,10))

In [74]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
arr_2d.shape

(10, 10)

In [80]:
for i in range(arr_2d.shape[0]):
    arr_2d[i] = i

In [81]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [82]:
arr_2d[[9,5,3,6]]

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

**Lecture 10**

In [83]:
arr = np.arange(50).reshape(10,5)

In [84]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [85]:
arr_t = arr.T

In [86]:
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [88]:
arr[9][4] = 999

In [89]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48, 999]])

In [90]:
arr_t

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [  1,   6,  11,  16,  21,  26,  31,  36,  41,  46],
       [  2,   7,  12,  17,  22,  27,  32,  37,  42,  47],
       [  3,   8,  13,  18,  23,  28,  33,  38,  43,  48],
       [  4,   9,  14,  19,  24,  29,  34,  39,  44, 999]])

In [91]:
arr[9][4] = 49

In [92]:
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [93]:
arr.dot(arr_t)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [94]:
arr_t.dot(arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [95]:
arr3 = np.arange(50).reshape(5,5,2)

In [96]:
arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [97]:
arr3.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [98]:
arr_n = np.array([[1,2,3]])

In [103]:
arr_n

array([[1, 2, 3]])

In [105]:
arr_n.swapaxes(0,1)

array([[1],
       [2],
       [3]])

**Lecture 11**

In [106]:
arr = np.arange(10)

In [107]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [110]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [112]:
A = np.random.randn(10)
B = np.random.randn(10)

In [114]:
A

array([-1.57154515, -1.73178266,  0.26022476,  1.03242554, -0.9343824 ,
        0.86110573, -1.17365322,  3.13684407,  1.18199466,  0.89583883])

In [115]:
B

array([ 2.34116348, -0.54864315, -1.30599312,  0.34209323, -1.97801067,
        0.10069976,  0.64062731,  0.23491636,  0.63115921, -1.8409179 ])

In [116]:
np.add(A,B)

array([ 0.76961833, -2.28042581, -1.04576836,  1.37451877, -2.91239307,
        0.96180549, -0.53302592,  3.37176043,  1.81315387, -0.94507906])

In [117]:
np.maximum(A,B)

array([ 2.34116348, -0.54864315,  0.26022476,  1.03242554, -0.9343824 ,
        0.86110573,  0.64062731,  3.13684407,  1.18199466,  0.89583883])

In [118]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True